-- 0044 — add 'refunded' to payment_status.
--
-- NOT YET APPLIED TO PRODUCTION. Test project only; production migrations are
-- applied by hand after review. Safe to re-run.
--
-- Its own file because Postgres will not let you use an enum value in the same
-- transaction that adds it, so this cannot be bundled with anything that then
-- writes 'refunded'. Nothing in 0045 would break if this were folded into it —
-- neither job_label nor notification_log references the value. It is split
-- anyway, because bundling an ADD VALUE with the UPDATE that uses it is
-- precisely the mistake, and the only defence that survives a careless later
-- edit is the value living in a file that contains nothing else.
--
-- WHY THE VALUE IS NEEDED
-- An on-time customer cancellation refunds the card and then nulls both
-- payment_status and payment_intent_id, so the job row ends up saying nothing
-- happened. The only surviving trace is a free-text note. Worse, nulling
-- payment_intent_id also breaks Stripe's own record: the charge.refunded
-- webhook finds its job by payment_intent_id, so by the time it arrives the
-- lookup matches nothing and the refund line is never written. One line of
-- code destroys two independent records of the same refund.
--
-- The fix is not to stop nulling payment_status — that is what keeps a
-- cancelled job out of anything reasoning about pending money. It is to record
-- 'refunded' explicitly and keep payment_intent_id, so the row still says which
-- charge was returned and a Stripe payout report can be walked back to a job.
--
-- WHY ONE VALUE AND NOT TWO
-- 'canceled' is deliberately NOT added. jobs.status already carries 'canceled',
-- and a second column that can disagree with it about whether a job is
-- cancelled is a reconciliation bug waiting to be filed. The client's
-- "refunded/canceled" is one display concept over two facts: status='canceled'
-- and payment_status='refunded'. The rendering rule lives in the application.
--
-- ORDERING — THIS ONE IS NOT MERELY DEGRADED
-- Most migrations in this project degrade to today's behaviour when they are
-- missing. This one does not. If this file is applied and the code is not,
-- nothing changes: no writer exists. But if the CODE deploys and this file has
-- NOT been applied, the UPDATE ... SET payment_status = 'refunded' throws
-- `invalid input value for enum payment_status` from inside the cancellation
-- path — AFTER the Stripe refund has already been issued. The customer's money
-- has gone back and the job row records nothing. Apply this BEFORE the deploy.

ALTER TYPE "payment_status" ADD VALUE IF NOT EXISTS 'refunded';

-- Check:  SELECT unnest(enum_range(NULL::payment_status));   -- 6 values, last is refunded
--
-- Rollback: there is none. Postgres has no ALTER TYPE ... DROP VALUE. An
-- unused enum value is harmless, but it is permanent — which is one more
-- reason it gets its own reviewed file.
--
-- Apply with (hand this to a human, do not run it):
--   psql "$PRODUCTION_DATABASE_URL" -f db/supabase/migrations/0044_payment_status_refunded.sql
